name: Lint

on:
  push:
    paths: "scripts/**"
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: psf/black@53a219056d1ab092ee2d4e5181c55c2e58c4756c
